# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbb640062eac271f19f94986c38d4ff1a2e912796d2689b2246cf57c19b6f8a5f579704ecf9aad82f0535e4ba2d412fc6910aa09d0561ed289bda033c21a69f2

test:
  secret_key_base: be169ef7705540822cc58736d963cb506b8f6837d2ab17aa2920d764e72791215b9ffbc0f67aca0089bd385780e19dad077be9ae042e56eb363304c5c5c0695b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
